version: "3.1"
services:
  postgress_database:
    container_name: postgress_database
    image: postgres
    environment:
      POSTGRES_DB: "lingo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test1234"
    ports:
      - "5432:5432"
    volumes:
      - postgress_db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  spring_boot:
    depends_on:
      - "postgress_database"
    build: .
    ports:
      - "9091:9091"
volumes:
  postgress_db_data: