version: "3.1"
services:
  mysql_database:
    container_name: lingoDatabase
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "lingo"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test1234"
      MYSQL_ROOT_PASSWORD: "test1234"
    ports:
      - "3322:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
volumes:
  mysql_db_data:
