version: "3.1"
services:
  mysql_database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "lingo"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test1234"
      MYSQL_ROOT_PASSWORD: "test1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
  spring_boot:
    depends_on:
      - "mysql_database"
    build: .
    ports:
      - "9091:9091"
#    volumes:
#      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
#      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2
volumes:
  mysql_db_data:
